-- KoleGame Arena Rooms v1
-- SAFE / ADDITIVE: does not alter, delete, truncate, or reset profiles/coins.
-- Run this ONCE in Supabase SQL Editor before uploading the new frontend.

create table if not exists public.kg_game_rooms (
  id bigint generated by default as identity primary key,
  code text not null unique check (code ~ '^[A-Z0-9]{6}$'),
  game text not null,
  host_id uuid not null references auth.users(id) on delete cascade,
  guest_id uuid references auth.users(id) on delete set null,
  status text not null default 'waiting' check (status in ('waiting','playing','finished','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists kg_game_rooms_code_idx on public.kg_game_rooms(code);
create index if not exists kg_game_rooms_host_idx on public.kg_game_rooms(host_id);
create index if not exists kg_game_rooms_guest_idx on public.kg_game_rooms(guest_id);

alter table public.kg_game_rooms enable row level security;

drop policy if exists "kg rooms participants can read" on public.kg_game_rooms;
create policy "kg rooms participants can read"
on public.kg_game_rooms for select
to authenticated
using (auth.uid() = host_id or auth.uid() = guest_id);

create or replace function public.kg_create_room(p_code text, p_game text)
returns public.kg_game_rooms
language plpgsql
security definer
set search_path = public
as $$
declare r public.kg_game_rooms;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if p_code !~ '^[A-Z0-9]{6}$' then raise exception 'invalid room code'; end if;
  if p_game not in ('rps','tictactoe','reaction','quiz','connect4','highlow','mathduel','color') then raise exception 'invalid game'; end if;

  -- Keep only the caller's old waiting rooms closed; no player/account data is touched.
  update public.kg_game_rooms
     set status='closed', updated_at=now()
   where host_id=auth.uid() and status='waiting';

  insert into public.kg_game_rooms(code,game,host_id,status)
  values (upper(p_code),p_game,auth.uid(),'waiting')
  returning * into r;
  return r;
exception when unique_violation then
  raise exception 'room code already exists';
end;
$$;

create or replace function public.kg_join_room(p_code text)
returns public.kg_game_rooms
language plpgsql
security definer
set search_path = public
as $$
declare r public.kg_game_rooms;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;

  select * into r
    from public.kg_game_rooms
   where code=upper(p_code) and status='waiting'
   for update;

  if not found then raise exception 'room not found or closed'; end if;
  if r.host_id=auth.uid() then return r; end if;
  if r.guest_id is not null then raise exception 'room is full'; end if;

  update public.kg_game_rooms
     set guest_id=auth.uid(), status='playing', updated_at=now()
   where id=r.id
   returning * into r;
  return r;
end;
$$;

create or replace function public.kg_leave_room(p_code text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare r public.kg_game_rooms;
begin
  if auth.uid() is null then return false; end if;
  update public.kg_game_rooms
     set status='closed', updated_at=now()
   where code=upper(p_code)
     and (host_id=auth.uid() or guest_id=auth.uid())
     and status in ('waiting','playing')
  returning * into r;
  return found;
end;
$$;

revoke all on function public.kg_create_room(text,text) from public;
revoke all on function public.kg_join_room(text) from public;
revoke all on function public.kg_leave_room(text) from public;
grant execute on function public.kg_create_room(text,text) to authenticated;
grant execute on function public.kg_join_room(text) to authenticated;
grant execute on function public.kg_leave_room(text) to authenticated;

-- Realtime is optional for the room table itself; the existing Presence/Broadcast channel
-- remains responsible for live gameplay. This migration only makes room creation/join atomic.
